// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqhGNXorQRM8_iFWutXfgVaWhkGFy9zY',
    appId: '1:218921576771:web:1ea0a9b1256d38ae3067f6',
    messagingSenderId: '218921576771',
    projectId: 'gestion-depence',
    authDomain: 'gestion-depence.firebaseapp.com',
    storageBucket: 'gestion-depence.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7f1rtajRglA7y9hSQnnCqPRrnfToTh0k',
    appId: '1:218921576771:android:2851b34089c063523067f6',
    messagingSenderId: '218921576771',
    projectId: 'gestion-depence',
    storageBucket: 'gestion-depence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hncV7l9pRBePS_H2Gd88-5N5J2pCRTk',
    appId: '1:218921576771:ios:a0f80311a86454a23067f6',
    messagingSenderId: '218921576771',
    projectId: 'gestion-depence',
    storageBucket: 'gestion-depence.firebasestorage.app',
    iosBundleId: 'com.example.gestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_hncV7l9pRBePS_H2Gd88-5N5J2pCRTk',
    appId: '1:218921576771:ios:a0f80311a86454a23067f6',
    messagingSenderId: '218921576771',
    projectId: 'gestion-depence',
    storageBucket: 'gestion-depence.firebasestorage.app',
    iosBundleId: 'com.example.gestion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoqhGNXorQRM8_iFWutXfgVaWhkGFy9zY',
    appId: '1:218921576771:web:8c20d5d7d3b3c9fc3067f6',
    messagingSenderId: '218921576771',
    projectId: 'gestion-depence',
    authDomain: 'gestion-depence.firebaseapp.com',
    storageBucket: 'gestion-depence.firebasestorage.app',
  );
}
